"""initial migration

Revision ID: 6a3761d44163
Revises: 
Create Date: 2026-06-20 20:06:31.100738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a3761d44163'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('role_title', sa.String(length=255), nullable=False),
    sa.Column('job_url', sa.String(length=500), nullable=True),
    sa.Column('source', sa.Enum('LinkedIn', 'Company Website', 'Referral', 'Indeed', 'Other', name='source_enum'), nullable=True),
    sa.Column('salary', sa.String(length=100), nullable=True),
    sa.Column('location_type', sa.Enum('Remote', 'Hybrid', 'Onsite', name='location_type_enum'), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('next_action_date', sa.Date(), nullable=True),
    sa.Column('current_status', sa.Enum('Applied', 'Screening', 'Technical Interview', 'Final Interview', 'Offer', 'Rejected', name='status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Applied', 'Screening', 'Technical Interview', 'Final Interview', 'Offer', 'Rejected', name='status_enum'), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_history')
    op.drop_table('applications')
    op.drop_table('users')
    # ### end Alembic commands ###
